echo '{"level":"info","message":"Info message for you"}'
echo '{"level":"debug","message":"Debug message for you"}'
echo ''
echo '{"level":"warn","message":"Warning message for you"}'
echo '{"level":"log","message":"Log message for you"}'
echo '{"level":"info","message":"Info message for you"}'
echo '{"message":"Invalid"}'
echo ''
echo '{"message":"Invalid again"}'
echo 'Success'