echo '{"logger":"Hello","level":"info","message":"Info message for you"}'
echo '{"logger":"Hello.info","level":"info","message":"Info message for you"}'
echo '{"logger":"Hello.debug","level":"debug","message":"Debug message for you"}'
echo '{"logger":"Hello.error","level":"error","message":"Error message for you"}'
echo '{"logger":"Hello.warn","level":"warn","message":"Warning message for you"}'
echo '{"logger":"Hello.log","level":"log","message":"Log message for you"}'
echo 'Success'
